# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '\\edu.local\public\studenthomes\22200322\Desktop\database_with_python-main\add_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(468, 361)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(50, 80, 331, 161))
        self.frame.setStyleSheet("background-color: rgb(52, 213, 186); border-radius: 20px")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.login = QtWidgets.QLineEdit(self.frame)
        self.login.setGeometry(QtCore.QRect(10, 10, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.login.setFont(font)
        self.login.setStyleSheet("border-radius: 20px; border: 2px solid; background-color: white")
        self.login.setObjectName("login")
        self.admin = QtWidgets.QRadioButton(self.frame)
        self.admin.setGeometry(QtCore.QRect(40, 110, 82, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.admin.setFont(font)
        self.admin.setObjectName("admin")
        self.client = QtWidgets.QRadioButton(self.frame)
        self.client.setGeometry(QtCore.QRect(190, 110, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.client.setFont(font)
        self.client.setChecked(True)
        self.client.setObjectName("client")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(110, 260, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.add_button.setFont(font)
        self.add_button.setStyleSheet("QPushButton:hover {\n"
"    background-color: #ffdbcc;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fcb9aa;\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(54, 213, 202);\n"
"    border-radius: 25px;\n"
"}")
        self.add_button.setObjectName("add_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 40, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(60, 140, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.password.setFont(font)
        self.password.setStyleSheet("border-radius: 20px; border: 2px solid")
        self.password.setObjectName("password")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login.setPlaceholderText(_translate("MainWindow", "Введите логин"))
        self.admin.setText(_translate("MainWindow", "Админ"))
        self.client.setText(_translate("MainWindow", "Клиент"))
        self.add_button.setText(_translate("MainWindow", "Добавить"))
        self.label.setText(_translate("MainWindow", "Добавить пользователя"))
        self.password.setPlaceholderText(_translate("MainWindow", "Введите пароль"))
